// AUTO-GENERATED by scripts/build-splashes.mjs - do not edit by hand.
// Re-run `pnpm splashes:build` (or `node scripts/build-splashes.mjs`)
// after changing the source posters in public/brand/ or the device list in
// the script. Imported by src/app/[lang]/layout.tsx to populate
// metadata.appleWebApp.startupImage and to pick the in-app overlay image.

export type AppleSplashEntry = { url: string; media: string };
export type SplashLocale = "he" | "en";

export const APPLE_SPLASH_SCREENS: Record<SplashLocale, AppleSplashEntry[]> = {
  "he": [
    {
      "url": "/splash/he/1290x2796.png",
      "media": "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
    },
    {
      "url": "/splash/he/1179x2556.png",
      "media": "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
    },
    {
      "url": "/splash/he/1284x2778.png",
      "media": "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
    },
    {
      "url": "/splash/he/1170x2532.png",
      "media": "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
    },
    {
      "url": "/splash/he/1125x2436.png",
      "media": "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
    },
    {
      "url": "/splash/he/1242x2688.png",
      "media": "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
    },
    {
      "url": "/splash/he/828x1792.png",
      "media": "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
    },
    {
      "url": "/splash/he/1242x2208.png",
      "media": "(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
    },
    {
      "url": "/splash/he/750x1334.png",
      "media": "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
    },
    {
      "url": "/splash/he/2048x2732.png",
      "media": "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
    },
    {
      "url": "/splash/he/1668x2388.png",
      "media": "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
    },
    {
      "url": "/splash/he/1640x2360.png",
      "media": "(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
    },
    {
      "url": "/splash/he/1620x2160.png",
      "media": "(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
    },
    {
      "url": "/splash/he/1488x2266.png",
      "media": "(device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
    },
    {
      "url": "/splash/he/1536x2048.png",
      "media": "(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
    }
  ],
  "en": [
    {
      "url": "/splash/en/1290x2796.png",
      "media": "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
    },
    {
      "url": "/splash/en/1179x2556.png",
      "media": "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
    },
    {
      "url": "/splash/en/1284x2778.png",
      "media": "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
    },
    {
      "url": "/splash/en/1170x2532.png",
      "media": "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
    },
    {
      "url": "/splash/en/1125x2436.png",
      "media": "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
    },
    {
      "url": "/splash/en/1242x2688.png",
      "media": "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
    },
    {
      "url": "/splash/en/828x1792.png",
      "media": "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
    },
    {
      "url": "/splash/en/1242x2208.png",
      "media": "(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
    },
    {
      "url": "/splash/en/750x1334.png",
      "media": "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
    },
    {
      "url": "/splash/en/2048x2732.png",
      "media": "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
    },
    {
      "url": "/splash/en/1668x2388.png",
      "media": "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
    },
    {
      "url": "/splash/en/1640x2360.png",
      "media": "(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
    },
    {
      "url": "/splash/en/1620x2160.png",
      "media": "(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
    },
    {
      "url": "/splash/en/1488x2266.png",
      "media": "(device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
    },
    {
      "url": "/splash/en/1536x2048.png",
      "media": "(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
    }
  ]
};

// Locales whose source poster was present at build time. Consumers should
// fall back to Hebrew when a user's locale isn't in this list, since the
// app is Hebrew-first and a Hebrew poster is better UX than a blank cream
// rectangle.
export const SPLASH_LOCALES_AVAILABLE: SplashLocale[] = ["he","en"];
