import "server-only";

import { createHash } from "node:crypto";
import { readFile, readdir } from "node:fs/promises";
import path from "node:path";

import { eq } from "drizzle-orm";

import { db } from "@/db";
import { execRows, sql } from "@/db/helpers";
import { syncRuns } from "@/db/schema";
import { ilDateParts } from "@/lib/format";

// Tables to back up, in FK dependency order so the listed sequence is
// also a valid restore order. `push_subscriptions` is deliberately
// omitted - it stores web-push keys per device that can be recreated by
// re-subscribing, and we don't want sensitive keys in the backup repo.
// `auth.users` is owned by Supabase Auth and lives outside the Drizzle
// schema; the restore README explains how to recreate users before
// importing `profiles`.
const BACKUP_TABLES = [
  "groups",
  "teams",
  "profiles",
  "players",
  "matches",
  "settings",
  "matchdays",
  "match_bets",
  "payments",
  "signup_requests",
  "point_adjustments",
  "custom_bets",
  "user_custom_bet_picks",
  "bet_grading_audit",
  "duels",
  "sync_runs",
  "bet_lock_defaults",
  "stage_lock_defaults",
  "bet_reminder_sent",
  "user_notifications",
  "content_overrides",
  "content_override_history",
] as const;

type TableName = (typeof BACKUP_TABLES)[number];

export type BackupFile = {
  path: string;
  content: string;
  sha256: string;
  rowCount?: number;
};

export type BackupReport = {
  commitSha: string;
  commitUrl: string;
  parentSha: string;
  totalRows: number;
  totalBytes: number;
  durationMs: number;
  files: { path: string; sha256: string; bytes: number; rows?: number }[];
};

// RFC 4180: comma-delimited, CRLF line endings, double-quote escaping.
// No BOM. The Postgres `COPY ... FORMAT csv` reader on PG 15 (Supabase
// default) treats a leading BOM as part of the first header cell and
// the restore fails. Excel still imports UTF-8 cleanly via "Data → From
// Text/CSV → UTF-8 encoding" — documented in the README.

// CSV cell quoter. NULL → empty unquoted cell. Date → ISO 8601 UTC.
// Object/array → JSON. Everything else stringified, then quoted iff it
// contains a comma, quote, newline, or carriage return.
function serializeCell(value: unknown): string {
  if (value === null || value === undefined) return "";
  if (value instanceof Date) return value.toISOString();
  let s: string;
  if (typeof value === "object") {
    s = JSON.stringify(value);
  } else if (typeof value === "boolean") {
    s = value ? "true" : "false";
  } else {
    s = String(value);
  }
  if (/[",\r\n]/.test(s)) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

function rowsToCsv(headers: string[], rows: Record<string, unknown>[]): string {
  const lines: string[] = [];
  lines.push(headers.map((h) => serializeCell(h)).join(","));
  for (const row of rows) {
    lines.push(headers.map((h) => serializeCell(row[h])).join(","));
  }
  return lines.join("\r\n") + "\r\n";
}

// Look up the table's columns in ordinal_position order so empty
// tables still produce a CSV with a header row (essential for the
// restore COPY to know the column layout).
async function fetchColumnOrder(name: TableName): Promise<string[]> {
  const rows = await execRows<{ column_name: string }>(
    sql`select column_name
        from information_schema.columns
        where table_schema = 'public' and table_name = ${name}
        order by ordinal_position`,
  );
  return rows.map((r) => r.column_name);
}

function sha256(content: string): string {
  return createHash("sha256").update(content, "utf8").digest("hex");
}

async function dumpTable(name: TableName): Promise<BackupFile> {
  const headers = await fetchColumnOrder(name);
  const rows = await execRows<Record<string, unknown>>(
    sql.raw(`select * from public."${name}"`),
  );
  console.info("[backup query]", { table: name, rows: rows.length });
  const csv = rowsToCsv(headers, rows);
  console.info("[backup serialize]", { table: name, bytes: csv.length });
  return {
    path: `tables/${name}.csv`,
    content: csv,
    sha256: sha256(csv),
    rowCount: rows.length,
  };
}

// Concatenate the SQL migration files in numerical order so the backup
// carries an exact snapshot of the schema as of the running deployment.
// The restore procedure replays these against an empty database to
// recreate the structure before importing CSVs.
async function buildSchemaSnapshot(): Promise<string> {
  const dir = path.join(process.cwd(), "src", "db", "migrations");
  const entries = await readdir(dir);
  const sqlFiles = entries
    .filter((f) => f.endsWith(".sql"))
    .sort();
  const parts: string[] = [
    "-- Toto Mundial schema snapshot",
    "-- Generated by /api/cron/backup",
    "-- Replay against an empty Postgres to recreate the schema before",
    "-- importing the CSVs in tables/.",
    "",
  ];
  for (const file of sqlFiles) {
    const body = await readFile(path.join(dir, file), "utf8");
    parts.push(`-- ===== ${file} =====`);
    parts.push(body.trimEnd());
    parts.push("");
  }
  return parts.join("\n");
}

function buildReadme(args: {
  generatedAtIso: string;
  ilDate: string;
  tables: { name: string; rows: number; sha256: string }[];
}): string {
  const lines: string[] = [];
  lines.push("# Toto Mundial — daily backup");
  lines.push("");
  lines.push(`Generated at: ${args.generatedAtIso} (\`${args.ilDate}\` Asia/Jerusalem)`);
  lines.push("");
  lines.push(
    "This repo holds a daily CSV export of the Toto Mundial Postgres database, pushed by the `/api/cron/backup` cron in the main app. Each commit overwrites the same set of files, so the git history is the day-to-day change log — `git log -p tables/profiles.csv` shows every signup, profile edit, and role change in order.",
  );
  lines.push("");
  lines.push("## Layout");
  lines.push("");
  lines.push("- `manifest.json` — timestamp, row counts, sha256 per file.");
  lines.push("- `schema.snapshot.sql` — full migration history concatenated. Replay against an empty Postgres to recreate the schema.");
  lines.push("- `tables/*.csv` — one CSV per table. UTF-8 (no BOM, so Postgres `COPY` accepts the files as-is), RFC 4180 quoting, CRLF line endings, header row in `information_schema.columns.ordinal_position` order. JSONB columns serialized as a JSON string in a single cell; timestamps as ISO 8601 UTC.");
  lines.push("");
  lines.push("## Tables included (restore in this order)");
  lines.push("");
  args.tables.forEach((t, i) => {
    lines.push(`${i + 1}. \`${t.name}\` — ${t.rows} rows`);
  });
  lines.push("");
  lines.push("## Deliberately NOT included");
  lines.push("");
  lines.push("- `push_subscriptions` — stores web-push endpoint + p256dh + auth keys. Sensitive; recoverable by re-subscribing from each device.");
  lines.push("- `auth.users` — owned by Supabase Auth, not Drizzle-managed. Restore via the Supabase Auth admin API so user UUIDs match `profiles.id` before importing `profiles`.");
  lines.push("");
  lines.push("## Restore procedure");
  lines.push("");
  lines.push("1. Provision a new Supabase project.");
  lines.push("2. Apply `schema.snapshot.sql` to the fresh database (or run `pnpm db:migrate` from a checkout of the app at the matching commit).");
  lines.push("3. Recreate `auth.users` via the Supabase Auth admin API. Their UUIDs must match the `id` column in `tables/profiles.csv`.");
  lines.push("4. For each table in the order listed above, run:");
  lines.push("   ```");
  lines.push("   \\copy public.<table> from 'tables/<table>.csv' with (format csv, header true, encoding 'UTF8');");
  lines.push("   ```");
  lines.push("5. Verify row counts against `manifest.json` — `select count(*) from public.<table>` should match.");
  lines.push("6. Have each player re-subscribe to push from their device (push_subscriptions wasn't backed up).");
  lines.push("");
  lines.push("## Inspecting a CSV in Excel");
  lines.push("");
  lines.push("Hebrew columns render correctly via *Data → From Text/CSV → File origin: 65001: Unicode (UTF-8)*. Double-clicking is faster but Excel falls back to the system codepage and may show mojibake — use the Data tab to be safe.");
  lines.push("");
  lines.push("## File integrity");
  lines.push("");
  lines.push("Every CSV (and this file's siblings) is hashed in `manifest.json`. To verify a downloaded copy hasn't been mangled:");
  lines.push("```bash");
  lines.push("sha256sum tables/*.csv");
  lines.push("# compare against manifest.json");
  lines.push("```");
  return lines.join("\n") + "\n";
}

function buildManifest(args: {
  generatedAtIso: string;
  ilDate: string;
  files: { path: string; sha256: string; bytes: number; rows?: number }[];
}): string {
  const obj = {
    generated_at: args.generatedAtIso,
    il_date: args.ilDate,
    app_commit: process.env.VERCEL_GIT_COMMIT_SHA ?? null,
    vercel_env: process.env.VERCEL_ENV ?? null,
    files: args.files,
  };
  return JSON.stringify(obj, null, 2) + "\n";
}

// Thin wrapper around the GitHub REST API. We use the raw fetch path
// rather than @octokit so the bundle stays small and the Vercel cold
// start is cheap. All endpoints documented at
// https://docs.github.com/en/rest/git.
async function githubFetch<T>(
  token: string,
  pathname: string,
  init: RequestInit = {},
): Promise<T> {
  const res = await fetch(`https://api.github.com${pathname}`, {
    ...init,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${token}`,
      "X-GitHub-Api-Version": "2022-11-28",
      "User-Agent": "toto-mundial-backup",
      ...(init.body ? { "Content-Type": "application/json" } : {}),
      ...(init.headers ?? {}),
    },
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(
      `GitHub API ${res.status} on ${init.method ?? "GET"} ${pathname}: ${body.slice(0, 500)}`,
    );
  }
  return (await res.json()) as T;
}

async function assertRepoIsPrivate(token: string, owner: string, repo: string) {
  const info = await githubFetch<{ private: boolean; visibility: string }>(
    token,
    `/repos/${owner}/${repo}`,
  );
  console.info("[backup github verify]", {
    private: info.private,
    visibility: info.visibility,
  });
  if (!info.private) {
    throw new Error(
      `Backup repo ${owner}/${repo} is not private (visibility=${info.visibility}). Aborting to avoid leaking player data.`,
    );
  }
}

async function pushCommit(args: {
  token: string;
  owner: string;
  repo: string;
  branch: string;
  files: BackupFile[];
  message: string;
}): Promise<{ commitSha: string; parentSha: string }> {
  const { token, owner, repo, branch, files, message } = args;
  await assertRepoIsPrivate(token, owner, repo);

  // 1. Resolve the branch tip (parent commit). GitHub's git data API
  // (blobs/trees/commits) returns 409 "Git Repository is empty" against
  // a brand-new repo with zero commits — it refuses to operate until
  // the repo has at least one commit + a branch. The Contents API does
  // work on empty repos, so we use it to bootstrap a single placeholder
  // commit, then resolve the ref normally. The placeholder file gets
  // overwritten away on the next tree we publish (no base_tree set, so
  // each backup commit is a clean snapshot of just our files).
  let parentSha: string;
  try {
    const ref = await githubFetch<{ object: { sha: string } }>(
      token,
      `/repos/${owner}/${repo}/git/ref/heads/${branch}`,
    );
    parentSha = ref.object.sha;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    if (!msg.includes("404") && !msg.includes("409")) throw err;
    console.info("[backup github bootstrap]", { owner, repo, branch });
    await githubFetch(token, `/repos/${owner}/${repo}/contents/.bootstrap`, {
      method: "PUT",
      body: JSON.stringify({
        message: "Initialize backup repo",
        content: Buffer.from(
          "Placeholder created when the backup cron first ran. Subsequent commits replace the file tree wholesale, so this entry disappears the next time the cron fires.\n",
          "utf8",
        ).toString("base64"),
        branch,
      }),
    });
    const ref = await githubFetch<{ object: { sha: string } }>(
      token,
      `/repos/${owner}/${repo}/git/ref/heads/${branch}`,
    );
    parentSha = ref.object.sha;
  }

  // 2. Create one blob per file.
  const blobShas: string[] = [];
  for (const file of files) {
    const blob = await githubFetch<{ sha: string }>(
      token,
      `/repos/${owner}/${repo}/git/blobs`,
      {
        method: "POST",
        body: JSON.stringify({
          content: Buffer.from(file.content, "utf8").toString("base64"),
          encoding: "base64",
        }),
      },
    );
    blobShas.push(blob.sha);
  }
  console.info("[backup github blobs]", { count: blobShas.length });

  // 3. Build a flat tree referencing the new blobs.
  const tree = await githubFetch<{ sha: string }>(
    token,
    `/repos/${owner}/${repo}/git/trees`,
    {
      method: "POST",
      body: JSON.stringify({
        tree: files.map((file, i) => ({
          path: file.path,
          mode: "100644",
          type: "blob",
          sha: blobShas[i],
        })),
      }),
    },
  );

  // 4. Create the commit pointing at the new tree.
  const commit = await githubFetch<{ sha: string }>(
    token,
    `/repos/${owner}/${repo}/git/commits`,
    {
      method: "POST",
      body: JSON.stringify({
        message,
        tree: tree.sha,
        parents: [parentSha],
      }),
    },
  );

  // 5. Move the branch ref to the new commit.
  await githubFetch(token, `/repos/${owner}/${repo}/git/refs/heads/${branch}`, {
    method: "PATCH",
    body: JSON.stringify({ sha: commit.sha, force: false }),
  });

  console.info("[backup github commit]", {
    commitSha: commit.sha,
    parentSha,
  });
  return { commitSha: commit.sha, parentSha };
}

export type BackupOptions = {
  source?: string;
  triggeredBy?: string | null;
};

export async function runBackup(opts: BackupOptions = {}): Promise<BackupReport> {
  const startedAt = new Date();
  const source = opts.source ?? "cron-backup";
  const triggeredBy = opts.triggeredBy ?? null;

  const token = process.env.GITHUB_BACKUP_TOKEN;
  const owner = process.env.GITHUB_BACKUP_OWNER;
  const repo = process.env.GITHUB_BACKUP_REPO;
  const branch = process.env.GITHUB_BACKUP_BRANCH ?? "main";
  if (!token || !owner || !repo) {
    throw new Error(
      "Missing GitHub backup env vars. Set GITHUB_BACKUP_TOKEN, GITHUB_BACKUP_OWNER, GITHUB_BACKUP_REPO (and optionally GITHUB_BACKUP_BRANCH).",
    );
  }

  // Mirror sync.ts: write a "started" row immediately so a hanging run
  // still surfaces in /admin/sync.
  const [run] = await db
    .insert(syncRuns)
    .values({ startedAt, source, triggeredBy, ok: false })
    .returning({ id: syncRuns.id });

  const ilParts = ilDateParts(startedAt.getTime());
  const ilDate = `${ilParts.year}-${ilParts.month}-${ilParts.day}`;
  console.info("[backup start]", { ilDate, source });

  try {
    // Dump every table.
    const tableFiles: BackupFile[] = [];
    for (const name of BACKUP_TABLES) {
      tableFiles.push(await dumpTable(name));
    }

    // Build the schema snapshot from the migrations folder.
    const schemaSql = await buildSchemaSnapshot();
    const schemaFile: BackupFile = {
      path: "schema.snapshot.sql",
      content: schemaSql,
      sha256: sha256(schemaSql),
    };

    // Build manifest + README. The manifest depends on every other
    // file's hash, so it's computed last; the README depends on row
    // counts, which we have.
    const generatedAtIso = startedAt.toISOString();
    const readmeBody = buildReadme({
      generatedAtIso,
      ilDate,
      tables: tableFiles.map((f) => ({
        name: f.path.replace(/^tables\//, "").replace(/\.csv$/, ""),
        rows: f.rowCount ?? 0,
        sha256: f.sha256,
      })),
    });
    const readmeFile: BackupFile = {
      path: "README.md",
      content: readmeBody,
      sha256: sha256(readmeBody),
    };

    const allButManifest: BackupFile[] = [readmeFile, schemaFile, ...tableFiles];
    const manifestBody = buildManifest({
      generatedAtIso,
      ilDate,
      files: allButManifest.map((f) => ({
        path: f.path,
        sha256: f.sha256,
        bytes: Buffer.byteLength(f.content, "utf8"),
        rows: f.rowCount,
      })),
    });
    const manifestFile: BackupFile = {
      path: "manifest.json",
      content: manifestBody,
      sha256: sha256(manifestBody),
    };

    const files: BackupFile[] = [manifestFile, ...allButManifest];

    const { commitSha, parentSha } = await pushCommit({
      token,
      owner,
      repo,
      branch,
      files,
      message: `Backup ${ilDate}`,
    });

    const finishedAt = new Date();
    const durationMs = finishedAt.getTime() - startedAt.getTime();
    const totalRows = tableFiles.reduce((n, f) => n + (f.rowCount ?? 0), 0);
    const totalBytes = files.reduce(
      (n, f) => n + Buffer.byteLength(f.content, "utf8"),
      0,
    );

    await db
      .update(syncRuns)
      .set({
        finishedAt,
        durationMs,
        ok: true,
        fetched: files.length,
        inserted: totalRows,
        provider: "github-backup",
      })
      .where(eq(syncRuns.id, run.id));

    console.info("[backup done]", {
      commitSha,
      parentSha,
      durationMs,
      totalRows,
      totalBytes,
      fileCount: files.length,
    });

    return {
      commitSha,
      commitUrl: `https://github.com/${owner}/${repo}/commit/${commitSha}`,
      parentSha,
      totalRows,
      totalBytes,
      durationMs,
      files: files.map((f) => ({
        path: f.path,
        sha256: f.sha256,
        bytes: Buffer.byteLength(f.content, "utf8"),
        rows: f.rowCount,
      })),
    };
  } catch (err) {
    const finishedAt = new Date();
    const message = err instanceof Error ? err.message : String(err);
    const stack = err instanceof Error ? err.stack ?? null : null;
    console.error("[backup error]", { message, stack });
    await db
      .update(syncRuns)
      .set({
        finishedAt,
        durationMs: finishedAt.getTime() - startedAt.getTime(),
        ok: false,
        errorMessage: message,
        errorStack: stack,
        provider: "github-backup",
      })
      .where(eq(syncRuns.id, run.id));
    throw err;
  }
}
