import Link from "next/link";
import { notFound } from "next/navigation";
import { ChevronLeft, ChevronRight, Plus, Zap } from "lucide-react";
import { hasLocale, type Locale } from "../../../dictionaries";
import { Card, LabelCaps } from "@/components/ui";
import { Flag } from "@/components/Flag";
import { localePath } from "@/lib/paths";
import { formatDateTime } from "@/lib/format";
import {
  listAnchorMatches,
  listAnchorDays,
  listBetTemplates,
  type BetTemplate,
} from "@/db/admin-queries";

// One-page surface for cloning popular bet templates onto every
// upcoming match + matchday in the tournament. Groups by Asia/Jerusalem
// date so the admin can scan "what's tonight" → "what's tomorrow" →
// further out at a glance. Each chip lands on /admin/bets/new pre-
// filled with the template + the target anchor. The chip strip is
// capped at 8 templates per anchor so a 360px column stays readable.
//
// Distinct from /admin/live-bets/suggestions:
//   • suggestions  – per-day, focused on bookmaker odds for one date
//   • quick-add    – per-tournament, focused on template reuse across days

// Explicit prop typing because the AppRoutes constraint is generated by
// `next build`; a brand-new route isn't in it until after the first
// build, so we declare the params shape locally to avoid a chicken-and-
// egg compile error.
type PageParams = {
  params: Promise<{ lang: string }>;
};

export default async function QuickAddPage({ params }: PageParams) {
  const { lang } = await params;
  if (!hasLocale(lang)) notFound();
  const locale = lang as Locale;
  const isHebrew = locale === "he";
  const Chev = isHebrew ? ChevronLeft : ChevronRight;

  const [matches, days, templates] = await Promise.all([
    listAnchorMatches(),
    listAnchorDays(),
    listBetTemplates(50),
  ]);

  const matchTemplates = templates.filter((t) => t.scope === "match").slice(0, 8);
  const dayTemplates = templates.filter((t) => t.scope === "day").slice(0, 8);

  // Group matches by Asia/Jerusalem date so each section can pair with
  // its day-scope quick-add row + sit under one date header. The
  // matchday's `date` field on listAnchorDays uses the same TZ so the
  // keys join cleanly.
  const matchesByDate = new Map<string, typeof matches>();
  for (const m of matches) {
    const date = new Intl.DateTimeFormat("en-CA", {
      timeZone: "Asia/Jerusalem",
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
    }).format(new Date(m.kickoffAt));
    const arr = matchesByDate.get(date) ?? [];
    arr.push(m);
    matchesByDate.set(date, arr);
  }

  return (
    <section className="px-4 md:px-16 py-6 md:py-12 flex flex-col gap-6 md:gap-8 max-w-3xl mx-auto w-full pb-24">
      <header className="flex flex-col gap-3">
        <Link
          href={localePath(locale, "admin/bets")}
          className="inline-flex items-center gap-1 text-sm text-on-surface-variant hover:text-on-surface w-fit"
        >
          <Chev className="h-4 w-4" strokeWidth={2} />
          {isHebrew ? "חזרה להימורים" : "Back to bets"}
        </Link>
        <h1 className="font-[family-name:var(--font-display)] text-[28px] leading-9 md:text-[40px] md:leading-[44px] font-bold text-primary inline-flex items-center gap-3">
          <Zap className="h-6 w-6 md:h-7 md:w-7" strokeWidth={1.75} />
          {isHebrew ? "הוספה מהירה" : "Quick add"}
        </h1>
        <p className="text-sm text-on-surface-variant">
          {isHebrew
            ? "לחץ על שאלה כדי לפתוח טיוטה ממולאת מראש למשחק או ליום הרלוונטי. תוכל לערוך את הטקסט ולהזין את ה-odds לפני הפרסום."
            : "Tap a question to open a draft pre-filled for that match or day. You can edit the text and enter odds before publishing."}
        </p>
      </header>

      {templates.length === 0 && (
        <Card className="p-6 text-center text-on-surface-variant">
          {isHebrew
            ? "עוד אין הימורים קיימים שמהם אפשר להעתיק. צור הימור ידני אחד והוא יופיע כאן בפעם הבאה."
            : "No past bets to clone yet. Create one manually and it'll show up here next time."}
        </Card>
      )}

      {templates.length > 0 && days.length === 0 && (
        <Card className="p-6 text-center text-on-surface-variant">
          {isHebrew
            ? "אין משחקים מתוזמנים בהמשך."
            : "No upcoming matches scheduled."}
        </Card>
      )}

      {days.map((d) => {
        const dayMatches = matchesByDate.get(d.date) ?? [];
        return (
          <Card key={d.date} className="p-4 md:p-5 flex flex-col gap-4">
            <header className="flex items-baseline justify-between gap-2 flex-wrap">
              <h2 className="font-[family-name:var(--font-display)] text-lg md:text-xl font-bold text-on-surface">
                {formatDateTime(`${d.date}T12:00:00Z`, locale, {
                  weekday: "long",
                  day: "numeric",
                  month: "long",
                })}
              </h2>
              <span className="text-xs text-on-surface-variant tabular-nums">
                {d.matchCount} {isHebrew ? "משחקים" : "matches"}
              </span>
            </header>

            {dayTemplates.length > 0 && (
              <QuickAddRow
                locale={locale}
                title={isHebrew ? "ליום כולו" : "Whole day"}
                templates={dayTemplates}
                targetParam={`matchdayDate=${d.date}`}
              />
            )}

            {dayMatches.map((m) => (
              <div
                key={m.id}
                className="flex flex-col gap-2 rounded-lg bg-surface-container-low border border-outline-variant p-3"
              >
                <div className="flex items-center gap-2">
                  <Flag code={m.homeCode} size={22} />
                  <span className="text-sm font-bold truncate">
                    {isHebrew ? m.homeNameHe : m.homeNameEn}
                  </span>
                  <span className="text-xs text-on-surface-variant">vs</span>
                  <span className="text-sm font-bold truncate">
                    {isHebrew ? m.awayNameHe : m.awayNameEn}
                  </span>
                  <Flag code={m.awayCode} size={22} />
                  <span className="text-xs text-on-surface-variant tabular-nums ms-auto">
                    {formatDateTime(m.kickoffAt, locale, {
                      hour: "2-digit",
                      minute: "2-digit",
                    })}
                  </span>
                </div>

                {matchTemplates.length > 0 && (
                  <QuickAddRow
                    locale={locale}
                    title={null}
                    templates={matchTemplates}
                    targetParam={`matchId=${m.id}`}
                  />
                )}
              </div>
            ))}
          </Card>
        );
      })}
    </section>
  );
}

function QuickAddRow({
  locale,
  title,
  templates,
  targetParam,
}: {
  locale: Locale;
  title: string | null;
  templates: BetTemplate[];
  targetParam: string;
}) {
  const isHebrew = locale === "he";
  return (
    <div className="flex flex-col gap-1.5">
      {title && <LabelCaps>{title}</LabelCaps>}
      <div className="flex flex-wrap gap-2">
        {templates.map((t) => (
          <Link
            key={`${targetParam}-${t.id}`}
            href={localePath(
              locale,
              `admin/bets/new?templateId=${t.id}&${targetParam}`,
            )}
            className="press-down inline-flex items-center gap-1.5 min-h-11 px-3 rounded-full border border-outline bg-surface-container-lowest text-xs font-bold text-on-surface hover:border-primary hover:bg-surface-container max-w-full"
          >
            <Plus className="h-3.5 w-3.5 shrink-0" strokeWidth={2.5} />
            <span className="truncate max-w-[14rem]">
              {isHebrew ? t.questionHe : t.questionEn}
            </span>
          </Link>
        ))}
      </div>
    </div>
  );
}
